name: Workflow

'on':
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0
    - name: Lint
      run: helm lint menero-helm-chart

  publish-chart:
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: stefanprodan/helm-gh-pages@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          charts_dir: .
          charts_repo_url: http://ehaupt.de/menero-helm-charts/
          owner: mahaupt
          repository: menero-helm-charts
          branch: release